# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181127_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='material',
            name='remark',
        ),
    ]
