# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181129_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='material',
        ),
        migrations.RemoveField(
            model_name='account',
            name='quantity',
        ),
        migrations.AddField(
            model_name='material',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
            preserve_default=False,
        ),
    ]
