# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181129_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
