# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181130_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Remark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='Remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
