# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181130_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='maerial_name',
            new_name='material_name',
        ),
        migrations.AddField(
            model_name='account',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
