# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181130_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
